"""Service table scheme added

Revision ID: 10dd11962ec5
Revises: 467d67bc91ce
Create Date: 2024-09-08 00:25:21.809391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dd11962ec5'
down_revision = '467d67bc91ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pet_name', sa.String(length=64), nullable=False),
    sa.Column('boarding_id', sa.Integer(), nullable=True),
    sa.Column('walk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boarding_id'], ['possible_pet_boarding.id'], ),
    sa.ForeignKeyConstraint(['pet_name'], ['pet.name'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['walk_id'], ['possible_walk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_username'))
        batch_op.drop_index(batch_op.f('ix_service_id'))

    op.drop_table('service')
    # ### end Alembic commands ###
