"""possible pet Boarding + PossibleWalking fix

Revision ID: 467d67bc91ce
Revises: 69d6bc611cfd
Create Date: 2024-09-08 00:20:18.857173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467d67bc91ce'
down_revision = '69d6bc611cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possible_pet_boarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_pets', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('possible_pet_boarding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_possible_pet_boarding_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_possible_pet_boarding_username'), ['username'], unique=False)

    with op.batch_alter_table('possible_walk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_hour', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('end_hour', sa.Time(), nullable=False))
        batch_op.drop_column('startHour')
        batch_op.drop_column('endHour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('possible_walk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endHour', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('startHour', sa.TIME(), nullable=False))
        batch_op.drop_column('end_hour')
        batch_op.drop_column('start_hour')

    with op.batch_alter_table('possible_pet_boarding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_possible_pet_boarding_username'))
        batch_op.drop_index(batch_op.f('ix_possible_pet_boarding_id'))

    op.drop_table('possible_pet_boarding')
    # ### end Alembic commands ###
