"""added possibleWalk table scheme

Revision ID: 69d6bc611cfd
Revises: bc8a50ca8aff
Create Date: 2024-09-08 00:16:16.303675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d6bc611cfd'
down_revision = 'bc8a50ca8aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possible_walk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_pets', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startHour', sa.Time(), nullable=False),
    sa.Column('endHour', sa.Time(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id', 'max_pets')
    )
    with op.batch_alter_table('possible_walk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_possible_walk_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_possible_walk_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('possible_walk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_possible_walk_username'))
        batch_op.drop_index(batch_op.f('ix_possible_walk_id'))

    op.drop_table('possible_walk')
    # ### end Alembic commands ###
