"""added pet_type to pet table scheme

Revision ID: 77c04ba1a8d1
Revises: 54b232db237d
Create Date: 2024-09-08 12:41:09.247306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c04ba1a8d1'
down_revision = '54b232db237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('pet_type')

    # ### end Alembic commands ###
