"""added avatar

Revision ID: 9bb63c6412ab
Revises: b9b5a38c3fe9
Create Date: 2024-09-07 13:52:26.842268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb63c6412ab'
down_revision = 'b9b5a38c3fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_avatar'), ['avatar'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatar'))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
