"""added pet table scheme

Revision ID: bc8a50ca8aff
Revises: 4172911e2efe
Create Date: 2024-09-08 00:01:55.020752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8a50ca8aff'
down_revision = '4172911e2efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=40), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('friendly', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('name', 'username')
    )
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_username'))
        batch_op.drop_index(batch_op.f('ix_pet_name'))

    op.drop_table('pet')
    # ### end Alembic commands ###
